// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rule.proto

// Package rule defines the serialized representation of a compiled .rule file
// passed from the ADE host to enforcement plugins over stdin.

package rule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvocationMode indicates whether the ADE host is running in compile or verify mode.
type InvocationMode int32

const (
	InvocationMode_MODE_UNSPECIFIED InvocationMode = 0
	InvocationMode_MODE_COMPILE     InvocationMode = 1
	InvocationMode_MODE_VERIFY      InvocationMode = 2
)

// Enum value maps for InvocationMode.
var (
	InvocationMode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_COMPILE",
		2: "MODE_VERIFY",
	}
	InvocationMode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_COMPILE":     1,
		"MODE_VERIFY":      2,
	}
)

func (x InvocationMode) Enum() *InvocationMode {
	p := new(InvocationMode)
	*p = x
	return p
}

func (x InvocationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[0].Descriptor()
}

func (InvocationMode) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[0]
}

func (x InvocationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationMode.Descriptor instead.
func (InvocationMode) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

// SelectorKind classifies the kind of element a Selector targets.
type SelectorKind int32

const (
	SelectorKind_SELECTOR_UNSPECIFIED SelectorKind = 0
	SelectorKind_SELECTOR_COMPONENT   SelectorKind = 1
	SelectorKind_SELECTOR_CLASS       SelectorKind = 2
	SelectorKind_SELECTOR_INTERFACE   SelectorKind = 3
	SelectorKind_SELECTOR_PATH        SelectorKind = 4
)

// Enum value maps for SelectorKind.
var (
	SelectorKind_name = map[int32]string{
		0: "SELECTOR_UNSPECIFIED",
		1: "SELECTOR_COMPONENT",
		2: "SELECTOR_CLASS",
		3: "SELECTOR_INTERFACE",
		4: "SELECTOR_PATH",
	}
	SelectorKind_value = map[string]int32{
		"SELECTOR_UNSPECIFIED": 0,
		"SELECTOR_COMPONENT":   1,
		"SELECTOR_CLASS":       2,
		"SELECTOR_INTERFACE":   3,
		"SELECTOR_PATH":        4,
	}
)

func (x SelectorKind) Enum() *SelectorKind {
	p := new(SelectorKind)
	*p = x
	return p
}

func (x SelectorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[1].Descriptor()
}

func (SelectorKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[1]
}

func (x SelectorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectorKind.Descriptor instead.
func (SelectorKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{1}
}

// RuleKind identifies the constraint expressed by a Rule.
type RuleKind int32

const (
	RuleKind_RULE_UNSPECIFIED     RuleKind = 0
	RuleKind_RULE_DEPEND_ONLY     RuleKind = 1
	RuleKind_RULE_NOT_DEPEND      RuleKind = 2
	RuleKind_RULE_ANNOTATE        RuleKind = 3
	RuleKind_RULE_NOT_ANNOTATE    RuleKind = 4
	RuleKind_RULE_EXTEND          RuleKind = 5
	RuleKind_RULE_NOT_EXTEND      RuleKind = 6
	RuleKind_RULE_IMPLEMENT       RuleKind = 7
	RuleKind_RULE_NOT_IMPLEMENT   RuleKind = 8
	RuleKind_RULE_ACCESSED_BY     RuleKind = 9
	RuleKind_RULE_ACYCLIC         RuleKind = 10
	RuleKind_RULE_IN              RuleKind = 11
	RuleKind_RULE_NOT_IN          RuleKind = 12
	RuleKind_RULE_MATCH           RuleKind = 13
	RuleKind_RULE_NOT_MATCH       RuleKind = 14
	RuleKind_RULE_VISIBILITY      RuleKind = 15
	RuleKind_RULE_TYPE_CONSTRAINT RuleKind = 16
)

// Enum value maps for RuleKind.
var (
	RuleKind_name = map[int32]string{
		0:  "RULE_UNSPECIFIED",
		1:  "RULE_DEPEND_ONLY",
		2:  "RULE_NOT_DEPEND",
		3:  "RULE_ANNOTATE",
		4:  "RULE_NOT_ANNOTATE",
		5:  "RULE_EXTEND",
		6:  "RULE_NOT_EXTEND",
		7:  "RULE_IMPLEMENT",
		8:  "RULE_NOT_IMPLEMENT",
		9:  "RULE_ACCESSED_BY",
		10: "RULE_ACYCLIC",
		11: "RULE_IN",
		12: "RULE_NOT_IN",
		13: "RULE_MATCH",
		14: "RULE_NOT_MATCH",
		15: "RULE_VISIBILITY",
		16: "RULE_TYPE_CONSTRAINT",
	}
	RuleKind_value = map[string]int32{
		"RULE_UNSPECIFIED":     0,
		"RULE_DEPEND_ONLY":     1,
		"RULE_NOT_DEPEND":      2,
		"RULE_ANNOTATE":        3,
		"RULE_NOT_ANNOTATE":    4,
		"RULE_EXTEND":          5,
		"RULE_NOT_EXTEND":      6,
		"RULE_IMPLEMENT":       7,
		"RULE_NOT_IMPLEMENT":   8,
		"RULE_ACCESSED_BY":     9,
		"RULE_ACYCLIC":         10,
		"RULE_IN":              11,
		"RULE_NOT_IN":          12,
		"RULE_MATCH":           13,
		"RULE_NOT_MATCH":       14,
		"RULE_VISIBILITY":      15,
		"RULE_TYPE_CONSTRAINT": 16,
	}
)

func (x RuleKind) Enum() *RuleKind {
	p := new(RuleKind)
	*p = x
	return p
}

func (x RuleKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[2].Descriptor()
}

func (RuleKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[2]
}

func (x RuleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleKind.Descriptor instead.
func (RuleKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{2}
}

// Visibility specifies an access modifier constraint on a type.
type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PUBLIC      Visibility = 1
	Visibility_VISIBILITY_INTERNAL    Visibility = 2
	Visibility_VISIBILITY_PRIVATE     Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_INTERNAL",
		3: "VISIBILITY_PRIVATE",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_INTERNAL":    2,
		"VISIBILITY_PRIVATE":     3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[3].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[3]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{3}
}

// TypeConstraint specifies a structural modifier constraint on a type.
type TypeConstraint int32

const (
	TypeConstraint_TYPE_CONSTRAINT_UNSPECIFIED TypeConstraint = 0
	TypeConstraint_TYPE_CONSTRAINT_ABSTRACT    TypeConstraint = 1
	TypeConstraint_TYPE_CONSTRAINT_SEALED      TypeConstraint = 2
	TypeConstraint_TYPE_CONSTRAINT_STATIC      TypeConstraint = 3
)

// Enum value maps for TypeConstraint.
var (
	TypeConstraint_name = map[int32]string{
		0: "TYPE_CONSTRAINT_UNSPECIFIED",
		1: "TYPE_CONSTRAINT_ABSTRACT",
		2: "TYPE_CONSTRAINT_SEALED",
		3: "TYPE_CONSTRAINT_STATIC",
	}
	TypeConstraint_value = map[string]int32{
		"TYPE_CONSTRAINT_UNSPECIFIED": 0,
		"TYPE_CONSTRAINT_ABSTRACT":    1,
		"TYPE_CONSTRAINT_SEALED":      2,
		"TYPE_CONSTRAINT_STATIC":      3,
	}
)

func (x TypeConstraint) Enum() *TypeConstraint {
	p := new(TypeConstraint)
	*p = x
	return p
}

func (x TypeConstraint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeConstraint) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[4].Descriptor()
}

func (TypeConstraint) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[4]
}

func (x TypeConstraint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeConstraint.Descriptor instead.
func (TypeConstraint) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{4}
}

// Severity controls whether a rule violation is a hard error or a warning.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_WARNING     Severity = 1
	Severity_SEVERITY_ERROR       Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_WARNING":     1,
		"SEVERITY_ERROR":       2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[5].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[5]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{5}
}

// ExcludeKind classifies what an Exclusion filters out.
type ExcludeKind int32

const (
	ExcludeKind_EXCLUDE_UNSPECIFIED         ExcludeKind = 0
	ExcludeKind_EXCLUDE_IMPLEMENT_INTERFACE ExcludeKind = 1
	ExcludeKind_EXCLUDE_CLASS               ExcludeKind = 2
	ExcludeKind_EXCLUDE_COMPONENT           ExcludeKind = 3
)

// Enum value maps for ExcludeKind.
var (
	ExcludeKind_name = map[int32]string{
		0: "EXCLUDE_UNSPECIFIED",
		1: "EXCLUDE_IMPLEMENT_INTERFACE",
		2: "EXCLUDE_CLASS",
		3: "EXCLUDE_COMPONENT",
	}
	ExcludeKind_value = map[string]int32{
		"EXCLUDE_UNSPECIFIED":         0,
		"EXCLUDE_IMPLEMENT_INTERFACE": 1,
		"EXCLUDE_CLASS":               2,
		"EXCLUDE_COMPONENT":           3,
	}
)

func (x ExcludeKind) Enum() *ExcludeKind {
	p := new(ExcludeKind)
	*p = x
	return p
}

func (x ExcludeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExcludeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[6].Descriptor()
}

func (ExcludeKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[6]
}

func (x ExcludeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExcludeKind.Descriptor instead.
func (ExcludeKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{6}
}

// CheckKind identifies the type of file system assertion in a Check.
type CheckKind int32

const (
	CheckKind_CHECK_UNSPECIFIED         CheckKind = 0
	CheckKind_CHECK_FS_MUST_EXIST       CheckKind = 1
	CheckKind_CHECK_FS_MUST_NOT_EXIST   CheckKind = 2
	CheckKind_CHECK_FS_MUST_CONTAIN     CheckKind = 3
	CheckKind_CHECK_FS_MUST_NOT_CONTAIN CheckKind = 4
)

// Enum value maps for CheckKind.
var (
	CheckKind_name = map[int32]string{
		0: "CHECK_UNSPECIFIED",
		1: "CHECK_FS_MUST_EXIST",
		2: "CHECK_FS_MUST_NOT_EXIST",
		3: "CHECK_FS_MUST_CONTAIN",
		4: "CHECK_FS_MUST_NOT_CONTAIN",
	}
	CheckKind_value = map[string]int32{
		"CHECK_UNSPECIFIED":         0,
		"CHECK_FS_MUST_EXIST":       1,
		"CHECK_FS_MUST_NOT_EXIST":   2,
		"CHECK_FS_MUST_CONTAIN":     3,
		"CHECK_FS_MUST_NOT_CONTAIN": 4,
	}
)

func (x CheckKind) Enum() *CheckKind {
	p := new(CheckKind)
	*p = x
	return p
}

func (x CheckKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[7].Descriptor()
}

func (CheckKind) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[7]
}

func (x CheckKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckKind.Descriptor instead.
func (CheckKind) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{7}
}

// Spec is the top-level envelope sent from the ADE host to each plugin.
// It carries the fully parsed and validated contents of a single .rule file.
type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adr           *Adr                   `protobuf:"bytes,1,opt,name=adr,proto3" json:"adr,omitempty"`
	Selectors     []*Selector            `protobuf:"bytes,2,rep,name=selectors,proto3" json:"selectors,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Mode          InvocationMode         `protobuf:"varint,4,opt,name=mode,proto3,enum=rule.InvocationMode" json:"mode,omitempty"`
	PluginConfig  map[string]string      `protobuf:"bytes,5,rep,name=plugin_config,json=pluginConfig,proto3" json:"plugin_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetAdr() *Adr {
	if x != nil {
		return x.Adr
	}
	return nil
}

func (x *Spec) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *Spec) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Spec) GetMode() InvocationMode {
	if x != nil {
		return x.Mode
	}
	return InvocationMode_MODE_UNSPECIFIED
}

func (x *Spec) GetPluginConfig() map[string]string {
	if x != nil {
		return x.PluginConfig
	}
	return nil
}

// Adr holds the identifying header declared at the top of a .rule file.
type Adr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adr) Reset() {
	*x = Adr{}
	mi := &file_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adr) ProtoMessage() {}

func (x *Adr) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adr.ProtoReflect.Descriptor instead.
func (*Adr) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{1}
}

func (x *Adr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Adr) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Selector is a named, reusable reference to a set of code elements or paths.
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Kind          SelectorKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=rule.SelectorKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{2}
}

func (x *Selector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Selector) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Selector) GetKind() SelectorKind {
	if x != nil {
		return x.Kind
	}
	return SelectorKind_SELECTOR_UNSPECIFIED
}

// Exclusion represents a single filter that narrows the subject set of a Rule.
type Exclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ExcludeKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=rule.ExcludeKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	mi := &file_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{3}
}

func (x *Exclusion) GetKind() ExcludeKind {
	if x != nil {
		return x.Kind
	}
	return ExcludeKind_EXCLUDE_UNSPECIFIED
}

func (x *Exclusion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// TargetRef is a reference to a rule subject or target — either a named
// selector or an inline pattern. The optional scope captures the "in <Scope>"
// qualifier from the DSL.
type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	IsInline      bool                   `protobuf:"varint,2,opt,name=is_inline,json=isInline,proto3" json:"is_inline,omitempty"`
	Kind          SelectorKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=rule.SelectorKind" json:"kind,omitempty"`
	IsMatch       bool                   `protobuf:"varint,4,opt,name=is_match,json=isMatch,proto3" json:"is_match,omitempty"`
	Scope         *TargetRef             `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{4}
}

func (x *TargetRef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TargetRef) GetIsInline() bool {
	if x != nil {
		return x.IsInline
	}
	return false
}

func (x *TargetRef) GetKind() SelectorKind {
	if x != nil {
		return x.Kind
	}
	return SelectorKind_SELECTOR_UNSPECIFIED
}

func (x *TargetRef) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

func (x *TargetRef) GetScope() *TargetRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

// Rule represents a single enforcement constraint within a Spec.
type Rule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind           RuleKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=rule.RuleKind" json:"kind,omitempty"`
	From           *TargetRef             `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Targets        []*TargetRef           `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Severity       Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=rule.Severity" json:"severity,omitempty"`
	Excludes       []*Exclusion           `protobuf:"bytes,6,rep,name=excludes,proto3" json:"excludes,omitempty"`
	Checks         []*Check               `protobuf:"bytes,7,rep,name=checks,proto3" json:"checks,omitempty"`
	Visibility     Visibility             `protobuf:"varint,8,opt,name=visibility,proto3,enum=rule.Visibility" json:"visibility,omitempty"`
	TypeConstraint TypeConstraint         `protobuf:"varint,9,opt,name=type_constraint,json=typeConstraint,proto3,enum=rule.TypeConstraint" json:"type_constraint,omitempty"`
	IsFileRule     bool                   `protobuf:"varint,10,opt,name=is_file_rule,json=isFileRule,proto3" json:"is_file_rule,omitempty"`
	IsCustomRule   bool                   `protobuf:"varint,11,opt,name=is_custom_rule,json=isCustomRule,proto3" json:"is_custom_rule,omitempty"`
	RawBody        string                 `protobuf:"bytes,12,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{5}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetKind() RuleKind {
	if x != nil {
		return x.Kind
	}
	return RuleKind_RULE_UNSPECIFIED
}

func (x *Rule) GetFrom() *TargetRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Rule) GetTargets() []*TargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Rule) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Rule) GetExcludes() []*Exclusion {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *Rule) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *Rule) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *Rule) GetTypeConstraint() TypeConstraint {
	if x != nil {
		return x.TypeConstraint
	}
	return TypeConstraint_TYPE_CONSTRAINT_UNSPECIFIED
}

func (x *Rule) GetIsFileRule() bool {
	if x != nil {
		return x.IsFileRule
	}
	return false
}

func (x *Rule) GetIsCustomRule() bool {
	if x != nil {
		return x.IsCustomRule
	}
	return false
}

func (x *Rule) GetRawBody() string {
	if x != nil {
		return x.RawBody
	}
	return ""
}

// Check represents a single file system assertion within a file Rule.
type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CheckKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=rule.CheckKind" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_rule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{6}
}

func (x *Check) GetKind() CheckKind {
	if x != nil {
		return x.Kind
	}
	return CheckKind_CHECK_UNSPECIFIED
}

func (x *Check) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Check) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

var File_rule_proto protoreflect.FileDescriptor

const file_rule_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rule.proto\x12\x04rule\"\xa1\x02\n" +
	"\x04Spec\x12\x1b\n" +
	"\x03adr\x18\x01 \x01(\v2\t.rule.AdrR\x03adr\x12,\n" +
	"\tselectors\x18\x02 \x03(\v2\x0e.rule.SelectorR\tselectors\x12 \n" +
	"\x05rules\x18\x03 \x03(\v2\n" +
	".rule.RuleR\x05rules\x12(\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x14.rule.InvocationModeR\x04mode\x12A\n" +
	"\rplugin_config\x18\x05 \x03(\v2\x1c.rule.Spec.PluginConfigEntryR\fpluginConfig\x1a?\n" +
	"\x11PluginConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x03Adr\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"`\n" +
	"\bSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12&\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x12.rule.SelectorKindR\x04kind\"H\n" +
	"\tExclusion\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.rule.ExcludeKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa8\x01\n" +
	"\tTargetRef\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1b\n" +
	"\tis_inline\x18\x02 \x01(\bR\bisInline\x12&\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x12.rule.SelectorKindR\x04kind\x12\x19\n" +
	"\bis_match\x18\x04 \x01(\bR\aisMatch\x12%\n" +
	"\x05scope\x18\x05 \x01(\v2\x0f.rule.TargetRefR\x05scope\"\xe0\x03\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x0e.rule.RuleKindR\x04kind\x12#\n" +
	"\x04from\x18\x03 \x01(\v2\x0f.rule.TargetRefR\x04from\x12)\n" +
	"\atargets\x18\x04 \x03(\v2\x0f.rule.TargetRefR\atargets\x12*\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x0e.rule.SeverityR\bseverity\x12+\n" +
	"\bexcludes\x18\x06 \x03(\v2\x0f.rule.ExclusionR\bexcludes\x12#\n" +
	"\x06checks\x18\a \x03(\v2\v.rule.CheckR\x06checks\x120\n" +
	"\n" +
	"visibility\x18\b \x01(\x0e2\x10.rule.VisibilityR\n" +
	"visibility\x12=\n" +
	"\x0ftype_constraint\x18\t \x01(\x0e2\x14.rule.TypeConstraintR\x0etypeConstraint\x12 \n" +
	"\fis_file_rule\x18\n" +
	" \x01(\bR\n" +
	"isFileRule\x12$\n" +
	"\x0eis_custom_rule\x18\v \x01(\bR\fisCustomRule\x12\x19\n" +
	"\braw_body\x18\f \x01(\tR\arawBody\"Z\n" +
	"\x05Check\x12#\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0f.rule.CheckKindR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern*I\n" +
	"\x0eInvocationMode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMODE_COMPILE\x10\x01\x12\x0f\n" +
	"\vMODE_VERIFY\x10\x02*\x7f\n" +
	"\fSelectorKind\x12\x18\n" +
	"\x14SELECTOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SELECTOR_COMPONENT\x10\x01\x12\x12\n" +
	"\x0eSELECTOR_CLASS\x10\x02\x12\x16\n" +
	"\x12SELECTOR_INTERFACE\x10\x03\x12\x11\n" +
	"\rSELECTOR_PATH\x10\x04*\xe0\x02\n" +
	"\bRuleKind\x12\x14\n" +
	"\x10RULE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RULE_DEPEND_ONLY\x10\x01\x12\x13\n" +
	"\x0fRULE_NOT_DEPEND\x10\x02\x12\x11\n" +
	"\rRULE_ANNOTATE\x10\x03\x12\x15\n" +
	"\x11RULE_NOT_ANNOTATE\x10\x04\x12\x0f\n" +
	"\vRULE_EXTEND\x10\x05\x12\x13\n" +
	"\x0fRULE_NOT_EXTEND\x10\x06\x12\x12\n" +
	"\x0eRULE_IMPLEMENT\x10\a\x12\x16\n" +
	"\x12RULE_NOT_IMPLEMENT\x10\b\x12\x14\n" +
	"\x10RULE_ACCESSED_BY\x10\t\x12\x10\n" +
	"\fRULE_ACYCLIC\x10\n" +
	"\x12\v\n" +
	"\aRULE_IN\x10\v\x12\x0f\n" +
	"\vRULE_NOT_IN\x10\f\x12\x0e\n" +
	"\n" +
	"RULE_MATCH\x10\r\x12\x12\n" +
	"\x0eRULE_NOT_MATCH\x10\x0e\x12\x13\n" +
	"\x0fRULE_VISIBILITY\x10\x0f\x12\x18\n" +
	"\x14RULE_TYPE_CONSTRAINT\x10\x10*p\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x17\n" +
	"\x13VISIBILITY_INTERNAL\x10\x02\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x03*\x87\x01\n" +
	"\x0eTypeConstraint\x12\x1f\n" +
	"\x1bTYPE_CONSTRAINT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TYPE_CONSTRAINT_ABSTRACT\x10\x01\x12\x1a\n" +
	"\x16TYPE_CONSTRAINT_SEALED\x10\x02\x12\x1a\n" +
	"\x16TYPE_CONSTRAINT_STATIC\x10\x03*N\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x02*q\n" +
	"\vExcludeKind\x12\x17\n" +
	"\x13EXCLUDE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEXCLUDE_IMPLEMENT_INTERFACE\x10\x01\x12\x11\n" +
	"\rEXCLUDE_CLASS\x10\x02\x12\x15\n" +
	"\x11EXCLUDE_COMPONENT\x10\x03*\x92\x01\n" +
	"\tCheckKind\x12\x15\n" +
	"\x11CHECK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHECK_FS_MUST_EXIST\x10\x01\x12\x1b\n" +
	"\x17CHECK_FS_MUST_NOT_EXIST\x10\x02\x12\x19\n" +
	"\x15CHECK_FS_MUST_CONTAIN\x10\x03\x12\x1d\n" +
	"\x19CHECK_FS_MUST_NOT_CONTAIN\x10\x04BR\n" +
	"\x18io.github.phi42.ade.ruleP\x01Z)github.com/phi42/ad-enforcement-tool/rule\xaa\x02\bAde.Ruleb\x06proto3"

var (
	file_rule_proto_rawDescOnce sync.Once
	file_rule_proto_rawDescData []byte
)

func file_rule_proto_rawDescGZIP() []byte {
	file_rule_proto_rawDescOnce.Do(func() {
		file_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)))
	})
	return file_rule_proto_rawDescData
}

var file_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rule_proto_goTypes = []any{
	(InvocationMode)(0), // 0: rule.InvocationMode
	(SelectorKind)(0),   // 1: rule.SelectorKind
	(RuleKind)(0),       // 2: rule.RuleKind
	(Visibility)(0),     // 3: rule.Visibility
	(TypeConstraint)(0), // 4: rule.TypeConstraint
	(Severity)(0),       // 5: rule.Severity
	(ExcludeKind)(0),    // 6: rule.ExcludeKind
	(CheckKind)(0),      // 7: rule.CheckKind
	(*Spec)(nil),        // 8: rule.Spec
	(*Adr)(nil),         // 9: rule.Adr
	(*Selector)(nil),    // 10: rule.Selector
	(*Exclusion)(nil),   // 11: rule.Exclusion
	(*TargetRef)(nil),   // 12: rule.TargetRef
	(*Rule)(nil),        // 13: rule.Rule
	(*Check)(nil),       // 14: rule.Check
	nil,                 // 15: rule.Spec.PluginConfigEntry
}
var file_rule_proto_depIdxs = []int32{
	9,  // 0: rule.Spec.adr:type_name -> rule.Adr
	10, // 1: rule.Spec.selectors:type_name -> rule.Selector
	13, // 2: rule.Spec.rules:type_name -> rule.Rule
	0,  // 3: rule.Spec.mode:type_name -> rule.InvocationMode
	15, // 4: rule.Spec.plugin_config:type_name -> rule.Spec.PluginConfigEntry
	1,  // 5: rule.Selector.kind:type_name -> rule.SelectorKind
	6,  // 6: rule.Exclusion.kind:type_name -> rule.ExcludeKind
	1,  // 7: rule.TargetRef.kind:type_name -> rule.SelectorKind
	12, // 8: rule.TargetRef.scope:type_name -> rule.TargetRef
	2,  // 9: rule.Rule.kind:type_name -> rule.RuleKind
	12, // 10: rule.Rule.from:type_name -> rule.TargetRef
	12, // 11: rule.Rule.targets:type_name -> rule.TargetRef
	5,  // 12: rule.Rule.severity:type_name -> rule.Severity
	11, // 13: rule.Rule.excludes:type_name -> rule.Exclusion
	14, // 14: rule.Rule.checks:type_name -> rule.Check
	3,  // 15: rule.Rule.visibility:type_name -> rule.Visibility
	4,  // 16: rule.Rule.type_constraint:type_name -> rule.TypeConstraint
	7,  // 17: rule.Check.kind:type_name -> rule.CheckKind
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_rule_proto_init() }
func file_rule_proto_init() {
	if File_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rule_proto_goTypes,
		DependencyIndexes: file_rule_proto_depIdxs,
		EnumInfos:         file_rule_proto_enumTypes,
		MessageInfos:      file_rule_proto_msgTypes,
	}.Build()
	File_rule_proto = out.File
	file_rule_proto_goTypes = nil
	file_rule_proto_depIdxs = nil
}
